name: .NET Core CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        cache: true
        cache-dependency-path: OffboardingChecklist/**/packages.lock.json
        
    - name: Restore dependencies
      run: dotnet restore OffboardingChecklist/OffboardingChecklist.csproj
      
    - name: Build
      run: dotnet build OffboardingChecklist/OffboardingChecklist.csproj --no-restore --configuration Release
      
    - name: Test
      run: dotnet test OffboardingChecklist/OffboardingChecklist.csproj --no-build --configuration Release --verbosity normal
      
    - name: Publish
      run: dotnet publish OffboardingChecklist/OffboardingChecklist.csproj --no-build --configuration Release --output ./publish
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: ./publish
        if-no-files-found: error

  docker:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        cd OffboardingChecklist
        docker build -t offboarding-checklist:latest .
        
    - name: Save Docker image
      run: docker save offboarding-checklist:latest | gzip > offboarding-checklist.tar.gz
      
    - name: Upload Docker image
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: offboarding-checklist.tar.gz
        if-no-files-found: error